# Generated by Django 3.0.3 on 2020-03-08 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photohireapp', '0003_auto_20200301_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photohireapp.Profile')),
            ],
        ),
    ]
